### ISSUE TITLE
project not building

### ISSUE THREAD

**Issue by moh1122** [learn-co-curriculum/FlatironGO#1]
Hello
Your project is soo nice but after building it. It got an error with exit code 1
i already run pod install but without any solution
can you help plz?

**Comment by JimCampagno** [comment]
@moh1122 

Can you send me a screenshot of this error you're receiving?

Questions I have, what version of Xcode are you running? I had few students download and run it here running Xcode Version 7.3.1 without any issues. When you download the project & run it--you should be met with a map displaying four treasures, when you tap a treasure you're brought to a black screen. I'm curious then as to how your environment is setup or the version of Xcode you have.
